package act6_grp8;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

class StudentInformation extends javax.swing.JFrame {

    /**
     * Creates new form StudentInformation
     */
    public StudentInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSex = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        lblHobbies = new javax.swing.JLabel();
        cbInternet = new javax.swing.JCheckBox();
        cbTV = new javax.swing.JCheckBox();
        chChat = new javax.swing.JCheckBox();
        cbGames = new javax.swing.JCheckBox();
        cbCook = new javax.swing.JCheckBox();
        cbMusic = new javax.swing.JCheckBox();
        lblCampus = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cmbCampus = new javax.swing.JComboBox<>();
        lblStudentNo = new javax.swing.JLabel();
        lblCollege = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblProgram = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        cmbCollege = new javax.swing.JComboBox<>();
        txtLastName = new javax.swing.JTextField();
        cmbProgram = new javax.swing.JComboBox<>();
        txtFirstName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtMiddleName = new javax.swing.JTextField();
        scrllpAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        scrllpRegistered = new javax.swing.JScrollPane();
        tblRegistered = new javax.swing.JTable();
        lblMiddleName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 680));

        lblSex.setText("Sex:");

        rbtnMale.setText("Male");

        rbtnFemale.setText("Female");

        lblHobbies.setText("Hobbies:");

        cbInternet.setText("Browsing Internet");

        cbTV.setText("Watching TV");

        chChat.setText("Chatting");

        cbGames.setText("Playing Games");

        cbCook.setText("Cooking");

        cbMusic.setText("Listening to Music");

        lblCampus.setText("Campus");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Student Information");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABUCAY", "BAGAC", "BALANGA", "DINALUPIHAN", "MAIN", "ORANI" }));

        lblStudentNo.setText("Student No.:");

        lblCollege.setText("College");

        lblName.setText("Student Name:");

        lblProgram.setText("Program");

        cmbCollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        scrllpAddress.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrllpAddress.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        scrllpAddress.setViewportView(txtAddress);

        lblLastName.setText("Last Name");

        lblFirstName.setText("First Name");

        scrllpRegistered.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        studentData = new String[tblRegistered.getRowCount()][3];
        ExpandableRow addRow = new ExpandableRow(studentData, txtFirstName.getText(), txtMiddleName.getText(), txtLastName.getText());
        addRow.setModel(tblRegistered);

        scrllpRegistered.setViewportView(tblRegistered);

        lblMiddleName.setText("Middle Name");

        lblAddress.setText("Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudentNo)
                                .addGap(32, 32, 32)
                                .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblAddress)
                                    .addComponent(lblSex)
                                    .addComponent(lblHobbies)
                                    .addComponent(lblCampus)
                                    .addComponent(lblCollege)
                                    .addComponent(lblProgram))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbProgram, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRegister)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rbtnMale)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbtnFemale))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cbInternet)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbTV)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(chChat))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(cbCook)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(cbGames))
                                                        .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbMusic))
                                                .addComponent(cmbCollege, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(scrllpAddress)))
                            .addComponent(scrllpRegistered))))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLastName)
                .addGap(132, 132, 132)
                .addComponent(lblFirstName)
                .addGap(125, 125, 125)
                .addComponent(lblMiddleName)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentNo)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(lblFirstName)
                    .addComponent(lblMiddleName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress)
                    .addComponent(scrllpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(rbtnMale)
                    .addComponent(rbtnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbInternet)
                    .addComponent(cbTV)
                    .addComponent(chChat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGames)
                    .addComponent(cbCook)
                    .addComponent(cbMusic)
                    .addComponent(lblHobbies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampus)
                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollege)
                    .addComponent(cmbCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram)
                    .addComponent(cmbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrllpRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        studentNum = txtStudentNo.getText();
        ExpandableRow addRow = new ExpandableRow();
        String[] rowData = {studentNum, txtFirstName.getText() + " " + txtMiddleName.getText() + " " + txtLastName.getText(), cmbProgram.getSelectedItem().toString()};
        addRow.addRow(rowData);
        for (int i = 0; i < tblRegistered.getRowCount(); i++) {
            studentData[i][0] = txtStudentNo.getText();
            studentData[i][1] = txtFirstName.getText() + " " + txtMiddleName.getText() + " " + txtLastName.getText();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    public javax.swing.JButton getButton() {
        return btnRegister;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentInformation().setVisible(true);
        });
    }
    
    private String[][] studentData;
    private String name;
    private String studentNum;
    private String program;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox cbCook;
    private javax.swing.JCheckBox cbGames;
    private javax.swing.JCheckBox cbInternet;
    private javax.swing.JCheckBox cbMusic;
    private javax.swing.JCheckBox cbTV;
    private javax.swing.JCheckBox chChat;
    public javax.swing.JComboBox<String> cmbCampus;
    public javax.swing.JComboBox<String> cmbCollege;
    public javax.swing.JComboBox<String> cmbProgram;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JLabel lblCollege;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHobbies;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMiddleName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblStudentNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JScrollPane scrllpAddress;
    private javax.swing.JScrollPane scrllpRegistered;
    public javax.swing.JTable tblRegistered;
    private javax.swing.JTextArea txtAddress;
    public javax.swing.JTextField txtFirstName;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtMiddleName;
    public javax.swing.JTextField txtStudentNo;
    // End of variables declaration//GEN-END:variables

}

final class ExpandableRow extends DefaultTableModel {

    DefaultTableModel tblmodelRegistered = new DefaultTableModel();
    String[][] studentData;

    public ExpandableRow(String[][] studentData, String fName, String mName, String lName, String prog) {
        super();
        this.studentData = new String[studentData.length][3];

        String name = fName + " " + mName + " " + lName;

        // Populate the array using a loop
        for (int i = 0; i < studentData.length; i++) {
            this.studentData[i][0] = studentData[i][0];
            this.studentData[i][1] = name;
            this.studentData[i][2] = studentData[i][1];
        }

        tblmodelRegistered = new DefaultTableModel(this.studentData, getColumnNames());
    }

    @Override
    public void addRow(Object[] rowData) {
        tblmodelRegistered.addRow(rowData);
    }

    public String[] getColumnNames() {
        return new String[]{"Student Number", "Student Name", "Program"};
    }

    public void setModel(javax.swing.JTable table) {
        table.setModel(tblmodelRegistered);
    }
}
