package OrderingModuleGrp8;

public class PizzaOrderFormGrp8 extends java.awt.Frame {

    /**
     * Creates new form PizzaOrderFormGrp8
     */
    public PizzaOrderFormGrp8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        lblName = new java.awt.Label();
        lblAddress = new java.awt.Label();
        txtName = new java.awt.TextField();
        txtAddress = new java.awt.TextField();
        lblFlavor = new java.awt.Label();
        lblPizzaSize = new java.awt.Label();
        lblDrinks = new java.awt.Label();
        lblDrinkSize = new java.awt.Label();
        lblPizzaPrice = new java.awt.Label();
        btnOrder = new java.awt.Button();
        listFlavor = new java.awt.List();
        txtPizzaPrice = new java.awt.TextField();
        cmbPizzaSize = new java.awt.Choice();
        cmbPizzaSize.add("Small");
        cmbPizzaSize.add("Medium");
        cmbPizzaSize.add("Large");
        cmbPizzaSize.add("Family");
        listDrinks = new java.awt.List();
        cmbDrinkSize = new java.awt.Choice();
        txtDrinkPrice = new java.awt.TextField();
        lblItemOrder = new java.awt.Label();
        lblPrice = new java.awt.Label();
        listOrder = new java.awt.List();
        lblDrinkPrice = new java.awt.Label();
        listPrice = new java.awt.List();
        lblAmtPay = new java.awt.Label();
        lblCash = new java.awt.Label();
        lblChange = new java.awt.Label();
        txtAmt = new java.awt.TextField();
        txtCash = new java.awt.TextField();
        txtChange = new java.awt.TextField();
        btnPay = new java.awt.Button();
        lblTotal = new java.awt.Label();
        lblTotalAmt = new java.awt.Label();
        insufficient = new java.awt.Label();
        errorName = new java.awt.Label();
        errorAddress = new java.awt.Label();

        setName("My Pizza Order Form"); // NOI18N
        setTitle("My Pizza Order Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lblName.setText("Customer Name");

        lblAddress.setText("Address");

        lblFlavor.setText("Flavor");

        lblPizzaSize.setText("Pizza Size");

        lblDrinks.setText("Drinks");

        lblDrinkSize.setText("Drink Size");

        lblPizzaPrice.setText("Pizza Price");

        btnOrder.setLabel("Place your Order");
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
        });

        listFlavor.setName("");
        listFlavor.add("Hawaiian");
        listFlavor.add("Ham & Cheese");
        listFlavor.add("Pepperoni");
        listFlavor.add("Overload");
        listFlavor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listFlavorItemStateChanged(evt);
            }
        });

        txtPizzaPrice.setText(String.valueOf(intPizzaSizePrice)
        );

        cmbPizzaSize.setName(""); // NOI18N
        cmbPizzaSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPizzaSizeItemStateChanged(evt);
            }
        });

        listDrinks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listDrinksItemStateChanged(evt);
            }
        });

        cmbDrinkSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDrinkSizeItemStateChanged(evt);
            }
        });

        txtDrinkPrice.setText(String.valueOf(intDrinkSizePrice)
        );

        lblItemOrder.setText("Item Ordered");

        lblPrice.setText("Price");

        lblDrinkPrice.setText("Drink Price");

        lblAmtPay.setText("Amount to Pay");

        lblCash.setText("Given Cash");

        lblChange.setText("Change");

        btnPay.setLabel("Pay Order");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        lblTotal.setText("Total");

        lblTotalAmt.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorName, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(errorAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listFlavor, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(lblFlavor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblItemOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPizzaSize, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPizzaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPizzaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbPizzaSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(listPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAmtPay, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(lblCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insufficient, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbDrinkSize, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrinkSize, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrinkPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrinkPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPizzaSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrinkSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPizzaSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDrinkSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPizzaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrinkPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPizzaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrinkPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(listPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(listOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(insufficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        listDrinks.add("Water");
        listDrinks.add("Sprite");
        listDrinks.add("Royal");
        listDrinks.add("Ice Tea");
        cmbDrinkSize.add("Regular");
        cmbDrinkSize.add("Large");

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void cmbPizzaSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPizzaSizeItemStateChanged
        switch (cmbPizzaSize.getSelectedItem()) {
            case "Small" ->
                intPizzaSizePrice = 300;
            case "Medium" ->
                intPizzaSizePrice = 450;
            case "Large" ->
                intPizzaSizePrice = 500;
            case "Family" ->
                intPizzaSizePrice = 550;
            default -> {
            }
        }
        txtPizzaPrice.setText(Integer.toString(intPizzaSizePrice));
    }//GEN-LAST:event_cmbPizzaSizeItemStateChanged

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        String name = txtName.getText();
        String address = txtAddress.getText();

        try {
            if (!name.isBlank() && !address.isBlank()) {
                getChange();
                errorName.setText("");
                errorAddress.setText("");
                if (getChange() < 0) {
                    txtChange.setText("--");
                    insufficient.setText("Insufficient Payment!");
                } else {
                    txtChange.setText(Integer.toString(getChange()));
                    insufficient.setText("");
                }
            } else {
                getChange();
                errorName.setText("Name cannot be empty!");
                errorAddress.setText("Address cannot be empty!");
            }
        } catch (NumberFormatException e) {
            errorName.setText("Name cannot be empty!");
            errorAddress.setText("Address cannot be empty!");
            insufficient.setText("Enter Cash Amount!");
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        int pizzaFlavorIndex = listFlavor.getSelectedIndex();
        String pizzaSize = cmbPizzaSize.getSelectedItem();
        int drinkIndex = listDrinks.getSelectedIndex();
        String drinkSize = cmbDrinkSize.getSelectedItem();

        if (pizzaFlavorIndex >= 0) {
            String pizzaFlavor = listFlavor.getItem(pizzaFlavorIndex);
            currentOrders.add(pizzaFlavor + " - " + pizzaSize);
            priceList.add(intPizzaSizePrice);
        }
        if (drinkIndex >= 0) {
            String drink = listDrinks.getItem(drinkIndex);
            currentOrders.add(drink + " - " + drinkSize);
            priceList.add(intDrinkSizePrice);
        }

        for (String item : currentOrders) {
            listOrder.add(item);
        }
        for (int item : priceList) {
            listPrice.add(Integer.toString(item));
        }

        // Clear the previous content of currentOrders
        currentOrders.clear();
        priceList.clear();

        lblTotalAmt.setText(Integer.toString(getTotalPrice()));
        txtAmt.setText(Integer.toString(getTotalPrice()));

        listFlavor.deselect(pizzaFlavorIndex);
        listDrinks.deselect(drinkIndex);
        txtCash.setText("");
        txtChange.setText("");
    }//GEN-LAST:event_btnOrderMouseClicked

    private void cmbDrinkSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDrinkSizeItemStateChanged
        switch (cmbDrinkSize.getSelectedItem()) {
            case "Regular" ->
                intDrinkSizePrice = 30;
            case "Large" ->
                intDrinkSizePrice = 50;
            default -> {
            }
        }
        txtDrinkPrice.setText(Integer.toString(intDrinkSizePrice));
    }//GEN-LAST:event_cmbDrinkSizeItemStateChanged

    private void listFlavorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listFlavorItemStateChanged
        evt.getSource().toString();
    }//GEN-LAST:event_listFlavorItemStateChanged

    private void listDrinksItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listDrinksItemStateChanged
        evt.getSource().toString();
    }//GEN-LAST:event_listDrinksItemStateChanged

    private int getTotalPrice() {
        int sum = 0;
        java.awt.List prices = listPrice;
        int size = prices.getItemCount();
        for (int i = 0; i < size; i++) {
            sum += Integer.parseInt(prices.getItem(i));
        }
        return sum;
    }

    private int getChange() {
        int sum = getTotalPrice();
        int cash = 0; 
        try {
            cash = Integer.parseInt(txtCash.getText());
            insufficient.setText("");
        } catch (NumberFormatException e) {
            insufficient.setText("Insufficient Payment!");
            txtChange.setText("--");
       
        }
        int change = cash - sum;
        return change;
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new PizzaOrderFormGrp8().setVisible(true);
        });
    }
    //Variables declaration
    int intPizzaSizePrice = 300,
            intDrinkSizePrice = 30;

    private final java.util.ArrayList<String> currentOrders = new java.util.ArrayList<>();
    private final java.util.ArrayList<Integer> priceList = new java.util.ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnOrder;
    private java.awt.Button btnPay;
    private java.awt.Choice cmbDrinkSize;
    private java.awt.Choice cmbPizzaSize;
    private java.awt.Label errorAddress;
    private java.awt.Label errorName;
    private java.awt.Label insufficient;
    private java.awt.Label lblAddress;
    private java.awt.Label lblAmtPay;
    private java.awt.Label lblCash;
    private java.awt.Label lblChange;
    private java.awt.Label lblDrinkPrice;
    private java.awt.Label lblDrinkSize;
    private java.awt.Label lblDrinks;
    private java.awt.Label lblFlavor;
    private java.awt.Label lblItemOrder;
    private java.awt.Label lblName;
    private java.awt.Label lblPizzaPrice;
    private java.awt.Label lblPizzaSize;
    private java.awt.Label lblPrice;
    private java.awt.Label lblTotal;
    private java.awt.Label lblTotalAmt;
    private java.awt.List list1;
    private java.awt.List listDrinks;
    private java.awt.List listFlavor;
    private java.awt.List listOrder;
    private java.awt.List listPrice;
    private java.awt.TextField txtAddress;
    private java.awt.TextField txtAmt;
    private java.awt.TextField txtCash;
    private java.awt.TextField txtChange;
    private java.awt.TextField txtDrinkPrice;
    private java.awt.TextField txtName;
    private java.awt.TextField txtPizzaPrice;
    // End of variables declaration//GEN-END:variables
}
